<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone Number or Email_regis-input</name>
   <tag></tag>
   <elementGuidId>30bbd03e-47c6-423f-af74-e5744bd0a1c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#regis-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='regis-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4fbb8260-919a-472f-b7b9-22703dc6292c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>41b372f6-e55b-48bc-b56d-3a8cde26b61b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-unify</name>
      <type>Main</type>
      <value>TextField</value>
      <webElementGuid>f83eb76d-2e69-4ff9-a5f7-7d14bb784b1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f76b4c2b-8919-4123-9807-4eea76cabcd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>regis-input</value>
      <webElementGuid>be020686-5677-4f27-87bf-c943fb7200fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>phone-email-input</value>
      <webElementGuid>3cdeb5dd-2d77-4bf4-919d-d843fa7525f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-ubsgp5 e110g5pc0</value>
      <webElementGuid>b12925ad-f656-4be8-9b55-79da8021123e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;regis-input&quot;)</value>
      <webElementGuid>1905380f-98b6-404b-86c4-65e2572cfd20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='regis-input']</value>
      <webElementGuid>6b773dbe-977b-430a-995f-ac1509322b74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zeus-root']/div/main/div[2]/div[2]/div/form/div/div/div/input</value>
      <webElementGuid>157dbb14-a59d-45de-a21e-0d29e4b39459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c9bff43c-5100-4e18-a615-c2d872bcf196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'regis-input']</value>
      <webElementGuid>866005d6-b24f-4a7f-b093-49c18a1de96f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
