<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Solusi</name>
   <tag></tag>
   <elementGuidId>a1a7b99f-c432-412c-ae8c-d75e0a7fb61e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.h-c-header__nav-li-link.navigation--item-secondary.material-icons-extended-pseudo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='zippy-solutions']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a16b7f27-62e0-4602-8e9f-b609bb1ae74a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-c-header__nav-li-link navigation--item-secondary material-icons-extended-pseudo</value>
      <webElementGuid>97e8eb8d-c4a4-4afb-a386-77764945ebe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-g-action</name>
      <type>Main</type>
      <value>solutions</value>
      <webElementGuid>e9c79ac6-0958-44e1-9317-e2a5672c0d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-g-event</name>
      <type>Main</type>
      <value>home: global nav</value>
      <webElementGuid>c29c19a0-6ea4-4190-a40b-a68a077ad63a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-g-label</name>
      <type>Main</type>
      <value>in-page interaction</value>
      <webElementGuid>c486e443-99c9-4138-b685-9c497f1031f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>event</name>
      <type>Main</type>
      <value>autotrack-data-g</value>
      <webElementGuid>b8dae5ab-2fad-49bd-9be5-b3be3b605c3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>54fc6887-b222-4703-8cf0-66ab942e2995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Solusi</value>
      <webElementGuid>c171e7fb-678a-4d64-bf7f-74e21a556e8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zippy-solutions&quot;)/a[@class=&quot;h-c-header__nav-li-link navigation--item-secondary material-icons-extended-pseudo&quot;]</value>
      <webElementGuid>f4609dd2-d536-4f6e-ad97-8fd909179a94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='zippy-solutions']/a</value>
      <webElementGuid>4a2a2c64-817d-44cf-bada-597cafcdf88d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more'])[1]/following::a[3]</value>
      <webElementGuid>3f501130-d6d7-4183-9e32-0521fa4bc60a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This site uses cookies from Google to deliver its services and to analyze traffic.'])[1]/following::a[4]</value>
      <webElementGuid>71e39be0-153c-4203-95c7-afc968548268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='close'])[1]/preceding::a[1]</value>
      <webElementGuid>b5bc53c6-a083-46f6-b592-5f8a1fd2ec56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[4]</value>
      <webElementGuid>0b5bb2f2-2f4f-42b2-b1c8-df4746e1f01d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>940810db-544e-4c32-af23-a45b3e8b1a91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Solusi' or . = 'Solusi')]</value>
      <webElementGuid>bbeaf4a9-54f3-47d0-92ef-78de9533ca47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
