<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_PT Telekomunikasi Selular, 2022_sp-fancybox-iframe sp-fancybox-skin sp-fancybox-iframe-410 adaptive-resolution</name>
   <tag></tag>
   <elementGuidId>2210aa2a-5251-4a4e-96c8-baaf92aab838</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[8]/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe.sp-fancybox-iframe.sp-fancybox-skin.sp-fancybox-iframe-410.adaptive-resolution</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>800c5dcb-5214-4657-b8f0-ea0aa1d29fd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>classname</name>
      <type>Main</type>
      <value>sp-fancybox-iframe sp-fancybox-skin sp-fancybox-iframe-410</value>
      <webElementGuid>3a554d7c-07e5-428d-aa11-a2cd8f3b4342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sp-fancybox-iframe sp-fancybox-skin sp-fancybox-iframe-410 adaptive-resolution</value>
      <webElementGuid>7e0b735f-2779-409e-9f41-2f87878e6c54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://mytelkomselprod.api.useinsider.com/api/info/frame?id=410&amp;version=1652772052&amp;isControlGroup=false</value>
      <webElementGuid>88f24205-a114-4af3-95da-004eb7141df1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>32697355-9aff-47e3-bef9-423335848250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js js tr-directwrite tr-aa-unknown-subpixel&quot;]/body[1]/div[@class=&quot;sp-fancybox-wrap sp-fancybox-wrap-410 sp-advanced-css-410 adaptive-resolution adaptive-position adaptive-x-position-center adaptive-y-position-middle&quot;]/iframe[@class=&quot;sp-fancybox-iframe sp-fancybox-skin sp-fancybox-iframe-410 adaptive-resolution&quot;]</value>
      <webElementGuid>8284b0eb-b4a4-4af3-9a31-6cc67ac9882a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/iframe</value>
      <webElementGuid>3510d316-ff54-4715-8acd-e2825cfed786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://mytelkomselprod.api.useinsider.com/api/info/frame?id=410&amp;version=1652772052&amp;isControlGroup=false']</value>
      <webElementGuid>30f04654-8ef4-4ec0-b154-447e86c02d3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
