<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_concat(id(, , img-image-1652771346526, , ))_img-image-1652771346526</name>
   <tag></tag>
   <elementGuidId>6412d6e5-f926-49c2-a2a3-f204c190eab6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='img-image-1652771346526']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#img-image-1652771346526</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>aacfa5dd-5af7-4de2-9486-2478272bd61c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://image.useinsider.com/mytelkomselprod/410/BpeSYG6PbAFyil3IcIef1652771345.jpeg</value>
      <webElementGuid>11881c1a-3bf5-4317-bb1c-e62ae53d32d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img-image-1652771346526</value>
      <webElementGuid>e2e4983d-0f3f-419d-ad62-7e2d99849d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>element-image</value>
      <webElementGuid>e8569aed-7869-49ec-98d8-468de0a67d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img-image-1652771346526&quot;)</value>
      <webElementGuid>a72bc063-0fdd-48ce-a57f-23143909c520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/page_telkomsel/Page_Beranda  Telkomsel/iframe_PT Telekomunikasi Selular, 2022_sp-fancybox-iframe sp-fancybox-skin sp-fancybox-iframe-410 adaptive-resolution</value>
      <webElementGuid>22ab1698-27f6-4b74-8de9-9d81c9d86e5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='img-image-1652771346526']</value>
      <webElementGuid>d4c18a34-897e-43cb-aafe-10525673fb4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='link-image-1652771346526']/img</value>
      <webElementGuid>067473be-091f-4a5f-a510-63a4281137c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://image.useinsider.com/mytelkomselprod/410/BpeSYG6PbAFyil3IcIef1652771345.jpeg')]</value>
      <webElementGuid>c96d4564-3ec0-417f-af2c-608cbf1695cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>30de72b5-d6be-407d-9336-4018a5949aca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://image.useinsider.com/mytelkomselprod/410/BpeSYG6PbAFyil3IcIef1652771345.jpeg' and @id = 'img-image-1652771346526']</value>
      <webElementGuid>7caf16ad-f724-4c2e-b4bf-758aaecc2496</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
