<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_by.U</name>
   <tag></tag>
   <elementGuidId>5737f5ca-0ac4-4f33-9561-a95a51315748</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navMobileDesktop']/ul/li[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>b94d4db2-87f7-401c-b2a0-22e1371fdd1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>by.U</value>
      <webElementGuid>192f7098-8eca-454b-b9a2-bc4205cd390d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navMobileDesktop&quot;)/ul[@class=&quot;main-sub-nav&quot;]/li[3]</value>
      <webElementGuid>1f2a1259-cde2-4e77-82e3-37445ae6fee7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navMobileDesktop']/ul/li[3]</value>
      <webElementGuid>4cd2093e-65b2-4532-b499-d72d1e666dc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Telkomsel Halo'])[1]/following::li[1]</value>
      <webElementGuid>69f7eed0-0a6a-45e0-aace-9d2ab505031d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Telkomsel PraBayar'])[1]/following::li[2]</value>
      <webElementGuid>a15c4fbe-b9fd-4c1d-b488-7ff764aa6d99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Roaming &amp; SLI'])[1]/preceding::li[1]</value>
      <webElementGuid>347dbe2a-ca09-4115-9818-56d05f15fb87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/ul/li[3]</value>
      <webElementGuid>978395f6-d666-44a7-86af-9e4c7fb219c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'by.U' or . = 'by.U')]</value>
      <webElementGuid>0fbb56a5-1943-4543-abaa-d4ea6c63d34d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
