<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CARI PENERBANGAN</name>
   <tag></tag>
   <elementGuidId>f1cbb52f-96fc-42a8-a17f-7c91c53f956b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.product-form-search-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='productWidget']/div[2]/div[3]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6503f851-b0b4-494b-99cf-9a8eb49b40c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-form-search-btn</value>
      <webElementGuid>6d78ca19-ece6-4234-ba97-f6567ff302d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CARI PENERBANGAN</value>
      <webElementGuid>7dcca2e1-7d84-4ddc-8cc2-bd410ae0d7f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productWidget&quot;)/div[@class=&quot;product-form&quot;]/div[@class=&quot;product-form-container product-form-button-group&quot;]/button[@class=&quot;product-form-search-btn&quot;]</value>
      <webElementGuid>cee8383f-491e-4e70-9e10-e84efbb21bd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='productWidget']/div[2]/div[3]/button</value>
      <webElementGuid>2f78bd39-b940-480c-babc-99afe73f4d86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SELESAI'])[1]/following::button[1]</value>
      <webElementGuid>434af549-4ed5-4832-8571-7dc61f24d034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First'])[1]/following::button[1]</value>
      <webElementGuid>99de590d-88c8-4de5-95fd-ba4666713d35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simple Profile'])[1]/preceding::button[1]</value>
      <webElementGuid>ccd57185-7dd3-4b19-b0c6-89badedd0923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simple Reschedule'])[1]/preceding::button[1]</value>
      <webElementGuid>3395117d-546f-474e-b344-76b646074dd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CARI PENERBANGAN']/parent::*</value>
      <webElementGuid>57624959-f4d7-4442-b628-d1782b625738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>26aac441-e315-4d0c-a48a-be41071af6d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'CARI PENERBANGAN' or . = 'CARI PENERBANGAN')]</value>
      <webElementGuid>464e7971-2e28-4ae4-8f87-1b8a6fb882ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
