<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Pesawat</name>
   <tag></tag>
   <elementGuidId>c6764b66-5bbc-4280-b0ad-487945ba358f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.product-box.active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='productWidget']/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0ce4595e-1551-4d26-aac0-ce66ff237faf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-box active</value>
      <webElementGuid>1cc9a029-2e38-4c8c-aad4-391eda6b9ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d5d88758-2439-4f6f-bfac-24d98acd5bcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pesawat</value>
      <webElementGuid>d65509d4-7214-422b-a2c7-631411ae35e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productWidget&quot;)/div[@class=&quot;product-list-container&quot;]/div[@class=&quot;product-list-content&quot;]/div[@class=&quot;product-box active&quot;]</value>
      <webElementGuid>ac472ae8-7bf1-4721-a481-4da379491797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1e89ae2a-1bdc-4f53-90c9-0f73c1f7c98f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-box active</value>
      <webElementGuid>237a42d0-4697-495f-895b-fc0e0c7cd1e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>dbe2c6ba-425d-4a24-b4a2-f4f6fb28157d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pesawat</value>
      <webElementGuid>794d1099-6139-4cbc-a297-47fcd5f95193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productWidget&quot;)/div[@class=&quot;product-list-container&quot;]/div[@class=&quot;product-list-content&quot;]/div[@class=&quot;product-box active&quot;]</value>
      <webElementGuid>93b28e6a-053f-4e6d-9544-d21508df0495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b90fd6e7-3450-4912-afc0-1c03f7960d77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-box active</value>
      <webElementGuid>a139d4a1-ac6a-4107-ba56-3449a41d1fe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f2148dd1-2535-490e-8990-b74c5e5ddd80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pesawat</value>
      <webElementGuid>8f63f067-acf2-45d2-86bb-d65d10f667b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productWidget&quot;)/div[@class=&quot;product-list-container&quot;]/div[@class=&quot;product-list-content&quot;]/div[@class=&quot;product-box active&quot;]</value>
      <webElementGuid>018d248b-7714-4ca8-85c6-55ef2724b1ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>98e61759-d00f-49dd-b045-d81b0b2a5092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-box active</value>
      <webElementGuid>70a45a11-6b92-4df4-b2f1-4001fb797ba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>34262b78-c4a2-4721-befa-553bca22cad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pesawat</value>
      <webElementGuid>9bb19191-57e0-4029-a06d-61436f345820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productWidget&quot;)/div[@class=&quot;product-list-container&quot;]/div[@class=&quot;product-list-content&quot;]/div[@class=&quot;product-box active&quot;]</value>
      <webElementGuid>faed43e0-e8d2-4562-8c78-de4ebb0a459d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3ecb875d-ffb1-425a-ac19-b0183635e750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-box active</value>
      <webElementGuid>74a6272f-084a-4a1b-a732-be7565d5bfd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>bebd7952-698c-4a75-98e8-7c8ff45e946c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pesawat</value>
      <webElementGuid>c04e5fb6-554a-4a5a-83ba-4a4e43848009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productWidget&quot;)/div[@class=&quot;product-list-container&quot;]/div[@class=&quot;product-list-content&quot;]/div[@class=&quot;product-box active&quot;]</value>
      <webElementGuid>f6d1e5dd-f037-4bdf-9461-b2e14ffbed17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='productWidget']/div/div[2]/div</value>
      <webElementGuid>2f7e0333-0dfd-447a-b42f-6d1d26361e94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mau ke mana?'])[1]/following::div[2]</value>
      <webElementGuid>005a7cab-1a0b-4532-a110-3a4b75d23343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hey, kamu'])[1]/following::div[2]</value>
      <webElementGuid>94f22435-d8a1-4992-842e-3c33ca5fbdcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hotel'])[2]/preceding::div[4]</value>
      <webElementGuid>ae313be6-1baf-4deb-a726-79c2441fb54f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/div[2]/div</value>
      <webElementGuid>3476b90e-a36e-46f6-aeb7-64088a48fb14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Pesawat' or . = 'Pesawat')]</value>
      <webElementGuid>f81bc7ab-1399-4b14-9f86-c81ffd1a6374</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
