<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DariPilih kota atau bandaraPopulerJakarta,</name>
   <tag></tag>
   <elementGuidId>a561ec20-1ffe-4624-ad55-9fcb636687d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fromInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fromInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ca53c2d4-a679-4d0b-816a-d1d75ab5774c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-to-input-group</value>
      <webElementGuid>963857dc-089c-4df6-9706-9e94a2f52805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fromInput</value>
      <webElementGuid>f617a0d0-bfb8-4d3a-b061-06a5fc8490e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DariPilih kota atau bandaraPopulerJakarta, IndonesiaJakartaJKTCSurabaya, IndonesiaSurabayaSUBCMedan, IndonesiaMedanMESCMakassar, IndonesiaMakassarUPGCYogyakarta, IndonesiaYogyakartaJOGCDenpasar-Bali, IndonesiaDenpasar-BaliDPSCPadang, IndonesiaPadangPDGCPalembang, IndonesiaPalembangPLMCBanjarmasin, IndonesiaBanjarmasinBDJCPontianak, IndonesiaPontianakPNKCTampilkan tiket FLEXITiket fleksibel yang bebas di-reschedule. Lihat detail.</value>
      <webElementGuid>11d8063a-4bb4-4904-a74e-b0e753f0625e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fromInput&quot;)</value>
      <webElementGuid>a87a7409-f385-4670-b9aa-94fc7f2701e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='fromInput']</value>
      <webElementGuid>7753bd0e-bb2b-4d61-b272-7ec08bc7c617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='productWidget']/div[2]/div[2]/div/div</value>
      <webElementGuid>db06429c-2886-4b0c-9545-f3f0dab1ebaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pulang-Pergi'])[1]/following::div[3]</value>
      <webElementGuid>2957a2d7-2221-4fac-9c13-cf3f05bee748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sekali Jalan'])[1]/following::div[5]</value>
      <webElementGuid>a75d442b-d9b9-48d3-8a34-e8adbe682d8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/div/div</value>
      <webElementGuid>cc5ce97c-3a25-44fe-827b-cec6fa05abb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'fromInput' and (text() = 'DariPilih kota atau bandaraPopulerJakarta, IndonesiaJakartaJKTCSurabaya, IndonesiaSurabayaSUBCMedan, IndonesiaMedanMESCMakassar, IndonesiaMakassarUPGCYogyakarta, IndonesiaYogyakartaJOGCDenpasar-Bali, IndonesiaDenpasar-BaliDPSCPadang, IndonesiaPadangPDGCPalembang, IndonesiaPalembangPLMCBanjarmasin, IndonesiaBanjarmasinBDJCPontianak, IndonesiaPontianakPNKCTampilkan tiket FLEXITiket fleksibel yang bebas di-reschedule. Lihat detail.' or . = 'DariPilih kota atau bandaraPopulerJakarta, IndonesiaJakartaJKTCSurabaya, IndonesiaSurabayaSUBCMedan, IndonesiaMedanMESCMakassar, IndonesiaMakassarUPGCYogyakarta, IndonesiaYogyakartaJOGCDenpasar-Bali, IndonesiaDenpasar-BaliDPSCPadang, IndonesiaPadangPDGCPalembang, IndonesiaPalembangPLMCBanjarmasin, IndonesiaBanjarmasinBDJCPontianak, IndonesiaPontianakPNKCTampilkan tiket FLEXITiket fleksibel yang bebas di-reschedule. Lihat detail.')]</value>
      <webElementGuid>54612680-b0e2-455e-a5b6-c7a20ba16893</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
