<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bisnis</name>
   <tag></tag>
   <elementGuidId>ce88eb53-0827-4400-aa20-b5a810b90036</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='passengerCabin']/div[2]/div/div/div[2]/div[2]/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1bdda105-ff49-4f6f-b416-24f38d713fa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>widget-passenger-cabin-type-container widget-cabin-type </value>
      <webElementGuid>e357d76c-8d0a-4cc3-a57d-74d4584486ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bisnis</value>
      <webElementGuid>42a83b19-1021-4bc4-930c-d1be32064074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;passengerCabin&quot;)/div[@class=&quot;widget-drop-down&quot;]/div[@class=&quot;widget-drop-down-content&quot;]/div[@class=&quot;passenger-cabin-drop-down-container&quot;]/div[@class=&quot;passenger-cabin-drop-down-content-container&quot;]/div[@class=&quot;passenger-cabin-content-list&quot;]/div[@class=&quot;passenger-cabin-item-list&quot;]/div[@class=&quot;widget-passenger-cabin-type-container widget-cabin-type&quot;]</value>
      <webElementGuid>4a74d69a-5fe1-4761-8053-81424a5bc2ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passengerCabin']/div[2]/div/div/div[2]/div[2]/div[3]/div</value>
      <webElementGuid>70df41dd-e079-4c9d-a017-5e8115b58bcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Premium Ekonomi'])[1]/following::div[2]</value>
      <webElementGuid>7d9c9a5e-bbde-4bd3-b473-f468ffc86a60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ekonomi'])[1]/following::div[5]</value>
      <webElementGuid>e7bdf408-3799-4939-8b10-6efa5a08a5f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First'])[1]/preceding::div[2]</value>
      <webElementGuid>dbd24e7c-6f36-4aca-9a6d-e3194c0cacec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div[2]/div[2]/div[3]/div</value>
      <webElementGuid>46e215c9-b072-43ca-92c0-43338d420c0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Bisnis' or . = 'Bisnis')]</value>
      <webElementGuid>092a4ecf-f0ec-4efc-a83e-e40110b16eb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
