<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_SELESAI</name>
   <tag></tag>
   <elementGuidId>51643c4c-3ddf-4864-bee4-231ae7a8c8a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.passenger-cabin-drop-down-text > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='passengerCabin']/div[2]/div/div/div[3]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a639f671-59a2-4019-99d9-3ca1944b3cc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1880319a-dd52-48fc-bb0b-696ca0820956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SELESAI</value>
      <webElementGuid>15e1ff50-90b0-45fd-87a9-c87278f99018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;passengerCabin&quot;)/div[@class=&quot;widget-drop-down&quot;]/div[@class=&quot;widget-drop-down-content&quot;]/div[@class=&quot;passenger-cabin-drop-down-container&quot;]/div[@class=&quot;passenger-cabin-drop-down-footer&quot;]/div[@class=&quot;passenger-cabin-drop-down-text&quot;]/span[1]</value>
      <webElementGuid>87af7cdb-2a06-4a28-a0db-b5c6ffdf9eaa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passengerCabin']/div[2]/div/div/div[3]/div/span</value>
      <webElementGuid>fe9da4c0-97ff-459c-bb57-a2a938549e3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First'])[1]/following::span[1]</value>
      <webElementGuid>b797f5c5-7bd1-4760-b4ee-51a446632ed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bisnis'])[1]/following::span[2]</value>
      <webElementGuid>029936ff-bcce-4a2b-a8f1-1633938a37a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CARI PENERBANGAN'])[1]/preceding::span[1]</value>
      <webElementGuid>af685f25-3637-4621-b4c1-035b09e3c9a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simple Profile'])[1]/preceding::span[1]</value>
      <webElementGuid>7e0173f6-d454-42cb-878f-b9a691a25a81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SELESAI']/parent::*</value>
      <webElementGuid>02426f62-828b-46a5-bd34-724d34f4317b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div/span</value>
      <webElementGuid>7c53e81a-7ce9-4e91-b4db-af18455065f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'SELESAI' or . = 'SELESAI')]</value>
      <webElementGuid>13f3f2cf-7ee5-4d36-8693-3e8a780b3be8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
